edition = "2021"
hard_tabs = true
use_field_init_shorthand = true
reorder_impl_items = true
unstable_features = true
wrap_comments = true
max_width = 100
chain_width = 80
control_brace_style = "ClosingNextLine"
imports_granularity = "Crate"
reorder_imports = true
