#!/usr/bin/env bash

FILE_PATH="$1"        # Full path of the previewed file
PREVIEW_X_COORD="$2"  # x coordinate of upper left cell of preview area
PREVIEW_Y_COORD="$3"  # y coordinate of upper left cell of preview area
PREVIEW_WIDTH="$4"    # Width of the preview pane (number of fitting characters)
PREVIEW_HEIGHT="$5"   # Height of the preview pane (number of fitting characters)

mimetype=$(file --mime-type -Lb "$FILE_PATH")

function kclear {
	kitty +kitten icat \
		--transfer-mode=file \
		--clear 2>/dev/null
}

function image {
	kitty +kitten icat \
		--transfer-mode=stream \
		--place "${PREVIEW_WIDTH}x${PREVIEW_HEIGHT}@${PREVIEW_X_COORD}x${PREVIEW_Y_COORD}" \
		"$1" 2>/dev/null
}

case "$mimetype" in
	image/*)
			kclear;
			image "$FILE_PATH";
		;;
	video/*)
			kclear;
			dirname="$(dirname "${FILE_PATH}")/.thumb";
			thumb="$(basename "${FILE_PATH}").jpg"
			absthumb="${dirname}/${thumb}";

			if [ ! -e "$dirname" ]; then
				mkdir "$dirname";
			fi;
	
			if [ ! -e "$absthumb" ]; then
				ffmpegthumbnailer -i "$FILE_PATH" -f -m -s 960 -o "$absthumb";
			fi;

		  if [ -z "$PREGEN" ]; then
				image "$absthumb";
			fi;
		;;
	*)
		kclear
		;;
esac

exit 0;
