# If joshuto does not know how to open the file, it can resort to opening it via xdg settings
xdg_open = true

# Collapse the preview window when there is no preview available
collapse_preview = false

# Ratios for parent view, current view and preview. You can specify 0 for
# parent view or omit it (So there are only 2 nums) and it won't be displayed
column_ratio = [1, 3, 4]


[preview]
max_preview_size            = 10737418240 # 10 G
preview_script              = "~/.config/joshuto/preview_file.sh" # make sure it's marked as executable
preview_shown_hook_script   = "~/.config/joshuto/on_preview_shown"
preview_removed_hook_script = "~/.config/joshuto/on_preview_removed"
